### ISSUE TITLE
descendant axis testcase

### ISSUE THREAD

**Issue by ufobat** [manwar/XML-XPath#3]
https://github.com/manwar/XML-XPath/blob/master/t/12axisdescendant.t#L11
shouldnt this be 10 instead of 11, because AAA (the root asix) should not be counted unless you use the axis descendant-or-self?

**Comment by manwar** [comment]
Hi @ufobat, 

Thanks for raising the issue.
Since I didn't write the original code, I may be wrong in my analysis.

I think you are assuming "/descendant::*" means root axis is "AAA". To prove this if you try instead "/AAA/descendant::*", you get the right count i.e. 10.

Just to double check my analysis, I went back to XML::LibXML and to my surprise, got the similar result.
Here is my sample code:

          use XML::LibXML;                                      
                                                      
          my $doc = XML::LibXML->new->parse_string('<AAA>       
          <BBB><DDD><CCC><DDD/><EEE/></CCC></DDD></BBB>         
          <CCC><DDD><EEE><DDD><FFF/></DDD></EEE></DDD></CCC>    
          </AAA>');                                             
                                                      
          my @nodes = $doc->findnodes('/descendant::*');        
          print "/descendant::* => ", scalar(@nodes), "\n";     
                                                      
          @nodes = $doc->findnodes('/AAA/descendant::*');    
          print "/AAA/descendant::* => ", scalar(@nodes), "\n"; 
 
Please correct me if I am missing anything.

Best Regards,
Mohammad S Anwar

**Comment by ufobat** [comment]
Hi Mohammad,
thanks for the Talk yesterday and the motivation to [fix](https://github.com/ufobat/p6-XML-XPath/commit/3c968d26d743c8c83ae07eaefdb893391b5c9dc7) an issue in my XML::XPath module. I think you missed one possible pull request ;)
