### ISSUE TITLE
treat @ARGV as utf8 string

### ISSUE THREAD

**Issue by GHolk** [manwar/XML-XPath#7]
i face some problem when using command line tool `xpath`.
when my query contain non-ascii string like `xpath -e '//*[contains(., "早安")'`,
xpath match nothing.
using `perl -CA` option to make perl treat `@ARGV` as utf8 fix this problem,
so it sould be caused by argv encoding problem.

i am not familiar with perl, so i am not sure what is the best solution
of argv encoding problem.

**Comment by grr** [comment]
read https://perldoc.perl.org/perlunitut#I/O-flow-(the-actual-5-minute-tutorial)

`@ARGV` is considered input to the program, so the user has to decode it. it is not done automatically.

**Comment by shawnw** [comment]
@grr True for your own programs, but for ones that are bundled as part of a module? They should be doing the decoding. But it's not as easy as just decoding UTF-8, because the input might not even *be* UTF-8 (cough Windows cough).

See [this stackoverflow question](https://stackoverflow.com/q/2037467/9952196) for some ways to do it portably.

**Comment by grr** [comment]
@shawnw, you're right- i overlooked you were referring to the program and not the module. note that your fix will require increasing the MIN_PERL_VERSION to 5.8 as  I18N::Langinfo is not dual-life (only ships with perl and not available separately):

    $ corelist I18N::Langinfo

    Data for 2022-04-20
    I18N::Langinfo was first released with perl v5.7.3

**Comment by shawnw** [comment]
I hope nobody's using a version that outdated, but I'll bump it anyways.
